-- Run in Supabase SQL editor

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  cislo_p text not null,
  nazov text not null,
  source text,
  kategoria text,
  slohy jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists songs_cislo_nazov_unique
  on public.songs (cislo_p, nazov);

alter table public.songs enable row level security;

drop policy if exists songs_read_all on public.songs;
create policy songs_read_all
  on public.songs
  for select
  using (true);

drop policy if exists songs_upsert_authenticated on public.songs;
create policy songs_upsert_authenticated
  on public.songs
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
