-- Run in Supabase SQL editor

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  cislo_p text not null,
  nazov text not null,
  source text,
  kategoria text,
  poradie_sloh text[],
  slohy jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

-- Ensure id is auto-generated even when the table already existed without identity/default.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'songs'
      and column_name = 'id'
      and is_identity = 'NO'
  ) then
    begin
      execute 'alter table public.songs alter column id add generated by default as identity';
    exception
      when others then
        -- Fallback for setups where adding identity is not possible.
        execute 'create sequence if not exists public.songs_id_seq';
        execute 'alter sequence public.songs_id_seq owned by public.songs.id';
        execute 'alter table public.songs alter column id set default nextval(''public.songs_id_seq'')';
    end;
  end if;
end $$;

-- Move id sequence to the next free value.
do $$
declare
  seq_name text;
  next_id bigint;
begin
  seq_name := pg_get_serial_sequence('public.songs', 'id');
  if seq_name is not null then
    select coalesce(max(id), 0) + 1 into next_id from public.songs;
    execute format('select setval(%L, %s, false)', seq_name, next_id);
  end if;
end $$;

alter table public.songs
  add column if not exists poradie_sloh text[];

drop index if exists songs_cislo_nazov_unique;

create index if not exists songs_cislo_nazov_idx
  on public.songs (cislo_p, nazov);

alter table public.songs enable row level security;

drop policy if exists songs_read_all on public.songs;
create policy songs_read_all
  on public.songs
  for select
  using (true);

drop policy if exists songs_upsert_authenticated on public.songs;
create policy songs_upsert_authenticated
  on public.songs
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
